services:
  bot:
    image: vpn-bot:${VPN_BOT_IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/data
      - ./assets:/app/assets
    networks:
      - web-server

networks:
  web-server:
    external: true
